### ISSUE TITLE
MultiThread時の多重Job起動失敗

### ISSUE THREAD

**Issue by hirakuriy** [terasoluna-batch/terasoluna-batch#3]
### 故障内容/エラー現象
【概要】
非同期ジョブにて同じジョブIDのジョブが同時に起動した場合に、ジョブの実行がエラーになることがある。
同時に実行したジョブの一部が起動エラー（BeanCreationException）になる場合がある。

【詳細】
非同期ジョブにて同じジョブIDのジョブ（または、異なるジョブでも同じDAO（Repository）を利用しているジョブ）が同じポーリングのタイミングにて別スレッドで起動した場合、同時に実行したジョブの一部が起動エラー（BeanCreationException）になる場合がある。
この事象が発生した場合、エラーとなったジョブの終了ステータスは「終了(2)」、終了コードは「255」になる。

### 発生条件/チェックポイント
①+②+③ or ①+②+④+⑤が該当するする場合に極稀に発生する。

① 「非同期型ジョブ実行機能」を利用して、多重スレッド起動している
　※ジョブBean定義ファイルに記述している task:executor タグの pool-size 属性の値(m-nと定義されていればnの方)が2以上の値になっている場合に該当。
　※task:executor タグが定義されていても、処理方式として「非同期型ジョブ実行機能」を利用していない場合は該当しない。
② 「非同期型ジョブ実行機能」を利用して起動されるジョブがMyBatisの機能（データアクセス機能）を利用している。
　※ジョブ管理テーブルへのアクセスを除くデータベースアクセスを行っていない（例：ファイル操作のみ、メール送信のみなど）場合は該当しない。

③複数のジョブBean定義ファイルに同じDao（Repository）クラスが定義されている

④ApplicationContextResolverImplを利用している。
　※CacheableApplicationContextResolverImplを利用していれば、該当しない
⑤同じジョブIDが同時に起動する（ジョブ管理テーブルに登録される）可能性がある　※業務要件に依存  

### 原因
【概要】
MｙBatis が提供する StrictMap#put に関する処理が同期化されていない。

【詳細】
MｙBatis が提供する StrictMap#put の処理が同一キーによる重複を許さないことに加え、StrictMap#put を実行する前の StrictMap への存在確認とその後の put の処理が同期化されておらず、あるスレッドAが該当する要素の存在確認を実施後、put をするまでの間に、別のスレッドBが存在確認をした場合に、スレッドB側の put 処理にて例外が発生してしまう。

## Possible Solutions
以下のいずれかの対応を実施する

■プロジェクトにて運用対処を実施する
当該ジョブ（終了ステータスは「終了(2)」、終了コードは「255」）を手動でリランして再実行することができるため、その結果を受けて運用対処する。
※ジョブ管理テーブルに登録されている該当ジョブのステータスを「未実施(0)」に、ビジネスロジック戻り値を空に変更する。

■ApplicationContextResolverImplにおけるresolveApplicationContext(BatchJobData) 内の処理を同期化する
ApplicationContextResolverImplを拡張し、MyBatisの初期化処理を呼び出すTERASOLUNA側のエントリポイントの処理となるresolveApplicationContext内部の処理を同期化する。
拡張したクラスを利用するようジョブBean定義ファイルを書き換える。

■CacheableApplicationContextResolverImplを利用する
ApplicationContextResolverImpl の代わりに TERASOLUNA Batch Framework for Java 3.6.x が提供している CacheableApplicationContextResolverImpl を利用するよう設定変更する。
なお、CacheableApplicationContextResolverImplに変更する際の注意点は下記参照。
・ジョブのインスタンスがシングルトンとして複数スレッド間で共用されるため、各ジョブがスレッドセーフな状態で実装されている必要がある。
・他のジョブで同じDaoクラス（Repository）が定義されていない必要がある。
・ジョブの種類が増えるとメモリへ影響する可能性がある。

## Affects Version/s
* 3.6.0.RELEASE
* 3.6.1.RELEASE
* 3.6.2.RELEASE
* 3.6.3.RELEASE

## Fix Version/s
3.6.x

## Issue Links
* #XXX

**Comment by takahashihrzg** [comment]
3.6.4で非同期ジョブ実行時のBean初期処理を同期化するように仕様変更したためクローズする
